const Quiz = require("../models/quiz");
const { generate } = require("../services/llm/llmService");
const Performance = require("../models/performance");

const generateQuiz = async (req, res) => {
    try {
        const {
            subject,
            topic,
            sessionId,
            numberOfQuestions = 5,
        } = req.body;

        if (!subject || !topic) {
            return res.status(400).json({
                message: "Subject and topic are required",
            });
        }

        const questionCount = Number(numberOfQuestions);

        if (
            !Number.isInteger(questionCount) ||
            questionCount < 1 ||
            questionCount > 10
        ) {
            return res.status(400).json({
                message: "Number of questions must be between 1 and 10",
            });
        }

        const prompt = `
Generate a ${questionCount}-question multiple choice quiz.

Subject:
${subject}

Topic:
${topic}

Rules:
1. Questions must test understanding, not just memorization.
2. Each question must have exactly 4 options.
3. Each question must have exactly one correct answer.
4. Difficulty should be appropriate for a student learning this topic.
5. Return ONLY valid JSON.
6. Do not use markdown.
7. Do not include explanations.

Return exactly this structure:

{
  "questions": [
    {
      "question": "Question text",
      "options": [
        "Option A",
        "Option B",
        "Option C",
        "Option D"
      ],
      "correctAnswer": "Option A"
    }
  ]
}
`;

        const llmPrompt = `
You generate educational multiple choice quizzes.

You MUST return ONLY valid JSON.

NEVER return:
- Markdown
- Code fences
- Explanations
- Comments
- Extra text
- Thinking/reasoning

The response MUST exactly follow this structure:

{
  "questions": [
    {
      "question": "string",
      "options": [
        "string",
        "string",
        "string",
        "string"
      ],
      "correctAnswer": "string"
    }
  ]
}

Rules:
1. Generate exactly ${questionCount} questions.
2. Every question must have exactly 4 options.
3. Every question must have exactly one correct answer.
4. correctAnswer MUST exactly match one of the four options.
5. Questions must be relevant to the given subject and topic.
6. Questions should test understanding rather than simple memorization.
7. Return complete JSON.
8. Do not stop before the JSON is complete.

${prompt}
`;

        const llmResponse = await generate(llmPrompt);

        let quizData;

        try {
            if (typeof llmResponse === "string") {
                quizData = JSON.parse(llmResponse);
            } else if (llmResponse?.content) {
                quizData =
                    typeof llmResponse.content === "string"
                        ? JSON.parse(llmResponse.content)
                        : llmResponse.content;
            } else {
                quizData = llmResponse;
            }
        } catch (parseError) {
            console.error("Quiz JSON parsing error:", parseError);
            console.error("LLM response:", llmResponse);

            return res.status(500).json({
                message: "Failed to parse quiz generated by AI",
            });
        }

        if (
            !quizData ||
            !Array.isArray(quizData.questions) ||
            quizData.questions.length !== questionCount
        ) {
            return res.status(500).json({
                message: "AI returned an invalid quiz format",
            });
        }

        // Validate every generated question
        for (const question of quizData.questions) {
            if (
                !question.question ||
                !Array.isArray(question.options) ||
                question.options.length !== 4 ||
                !question.correctAnswer ||
                !question.options.includes(question.correctAnswer)
            ) {
                return res.status(500).json({
                    message: "AI generated an invalid question format",
                });
            }
        }

        const quiz = await Quiz.create({
            student: req.user._id,
            subject,
            topic,
            sessionId: sessionId || null,
            questions: quizData.questions.map((question) => ({
                question: question.question,
                options: question.options,
                correctAnswer: question.correctAnswer,
            })),
            totalQuestions: questionCount,
            completed: false,
        });

        // Do not send correct answers to the frontend
        const questionsForStudent = quiz.questions.map((question, index) => ({
            _id: question._id,
            questionNumber: index + 1,
            question: question.question,
            options: question.options,
        }));

        return res.status(201).json({
            message: "Quiz generated successfully",
            quizId: quiz._id,
            subject: quiz.subject,
            topic: quiz.topic,
            totalQuestions: quiz.totalQuestions,
            questions: questionsForStudent,
        });
    } catch (error) {
        console.error("Generate quiz error:", error);

        return res.status(500).json({
            message: "Server error while generating quiz",
        });
    }
};


const submitQuiz = async (req, res) => {
  try {
    const { quizId, answers } = req.body;

    if (!quizId || !Array.isArray(answers)) {
      return res.status(400).json({
        message: "Quiz ID and answers are required",
      });
    }

    // Find the quiz belonging to the logged-in student
    const quiz = await Quiz.findOne({
      _id: quizId,
      student: req.user._id,
    });

    if (!quiz) {
      return res.status(404).json({
        message: "Quiz not found",
      });
    }

    // Prevent submitting the same quiz twice
    if (quiz.completed) {
      return res.status(400).json({
        message: "This quiz has already been submitted",
      });
    }

    // -----------------------------------------
    // 1. Calculate quiz result
    // -----------------------------------------

    let correctAnswers = 0;

    quiz.questions.forEach((question) => {
      const submittedAnswer = answers.find(
        (answer) =>
          String(answer.questionId) === String(question._id)
      );

      const selectedAnswer =
        submittedAnswer?.selectedAnswer || "";

      question.selectedAnswer = selectedAnswer;

      question.isCorrect =
        selectedAnswer === question.correctAnswer;

      if (question.isCorrect) {
        correctAnswers++;
      }
    });

    const totalQuestions = quiz.questions.length;

    const score =
      totalQuestions > 0
        ? (correctAnswers / totalQuestions) * 100
        : 0;

    // -----------------------------------------
    // 2. Update Quiz document
    // -----------------------------------------

    quiz.correctAnswers = correctAnswers;
    quiz.score = Math.round(score);
    quiz.completed = true;

    await quiz.save();

    // -----------------------------------------
    // 3. Find or create Performance document
    // -----------------------------------------

    let performance = await Performance.findOne({
      student: req.user._id,
    });

    if (!performance) {
      performance = new Performance({
        student: req.user._id,
        overallScore: 0,
        totalAssessments: 0,
        totalQuestions: 0,
        totalCorrectAnswers: 0,
        topics: [],
      });
    }

    // -----------------------------------------
    // 4. Update overall performance
    // -----------------------------------------

    performance.totalAssessments += 1;
    performance.totalQuestions += totalQuestions;
    performance.totalCorrectAnswers += correctAnswers;

    // Calculate overall score from all questions
    if (performance.totalQuestions > 0) {
      performance.overallScore = Math.round(
        (performance.totalCorrectAnswers /
          performance.totalQuestions) *
          100
      );
    }

    // -----------------------------------------
    // 5. Find existing topic
    // -----------------------------------------

    const existingTopic = performance.topics.find(
      (item) =>
        item.subject.toLowerCase() ===
          quiz.subject.toLowerCase() &&
        item.topic.toLowerCase() ===
          quiz.topic.toLowerCase()
    );

    // -----------------------------------------
    // 6. Update existing topic
    // -----------------------------------------

    if (existingTopic) {
      existingTopic.attempts += 1;

      existingTopic.totalQuestions += totalQuestions;

      existingTopic.correctAnswers += correctAnswers;

      // Calculate topic score from ALL attempts
      existingTopic.score = Math.round(
        (existingTopic.correctAnswers /
          existingTopic.totalQuestions) *
          100
      );

      // Determine topic level
      if (existingTopic.score < 50) {
        existingTopic.level = "weak";
      } else if (existingTopic.score < 75) {
        existingTopic.level = "average";
      } else {
        existingTopic.level = "strong";
      }

      existingTopic.lastAttemptAt = new Date();
    }

    // -----------------------------------------
    // 7. Create new topic
    // -----------------------------------------

    else {
      performance.topics.push({
        subject: quiz.subject,
        topic: quiz.topic,
        attempts: 1,
        totalQuestions: totalQuestions,
        correctAnswers: correctAnswers,
        score: Math.round(score),
        level:
          score < 50
            ? "weak"
            : score < 75
              ? "average"
              : "strong",
        lastAttemptAt: new Date(),
      });
    }

    // -----------------------------------------
    // 8. Save Performance
    // -----------------------------------------

    await performance.save();

    // -----------------------------------------
    // 9. Return result
    // -----------------------------------------

    return res.status(200).json({
      message: "Quiz submitted successfully",

      quizId: quiz._id,

      totalQuestions,

      correctAnswers,

      score: Math.round(score),

      performance: {
        overallScore: performance.overallScore,
        totalAssessments: performance.totalAssessments,
        totalQuestions: performance.totalQuestions,
        totalCorrectAnswers:
          performance.totalCorrectAnswers,
      },
    });
  } catch (error) {
    console.error("Submit quiz error:", error);

    return res.status(500).json({
      message: "Server error while submitting quiz",
    });
  }
};


module.exports = {
    generateQuiz,
    submitQuiz,
};